### ISSUE TITLE
Purpose of functions like ts_mean, ts_spike etc

### ISSUE THREAD

**Issue by pr1498** [gimpgael/ExtremeEventForecasting#1]
Hi gimpgael,
I'm working on an event forecasting project, and would like to clarify my doubt. According to my understanding of the Uber paper the LSTM autoencoder is used for feature extraction, then what's the point of having those functions which are also doing feature extraction ?

Thanks!

**Comment by gimpgael** [comment]
Hello pr1498,

Understand your point, but from my reading this is not the case. I understand they look at several way to characterize a time series (entropy, crossing points ...) and then the autoencoder to compress the info.

**Comment by pr1498** [comment]
I see! Thanks!
